import type { GalleryItem } from "../interface/interface";
import { Images } from "../utils/assets";

export const galleryItems: GalleryItem[] = [
  {
    id: 1,
    title: "Sensodyne - WDD Microsite",
    tech: "HTML/CSS/JS + PHP",
    liveUrl: "https://sensodyne-wdd-23.xplab.in/",
    src: Images.projects.sensodyne,
    alt: "Sensodyne Project",
  },
  {
    id: 2,
    title: "5 Star x YTFF - MD",
    tech: "HTML/CSS/JS + PHP",
    liveUrl: "https://5star-ytff-23.onmlab.in/",
    src: Images.projects.fiveStar,
    alt: "5 Star YTFF",
  },
  {
    id: 3,
    title: "CDM - Sittogether x ICC",
    tech: "HTML/CSS/JS + PHP",
    liveUrl: "https://cdm-sittogether.onmlab.in/",
    src: Images.projects.cdmSitTogether,
    alt: "Cadbury ICC",
  },
  {
    id: 4,
    title: "ITC Mixpod",
    tech: "HTML/CSS/JS + PHP",
    liveUrl: "https://mixpod-main.onmlab.in/",
    src: Images.projects.mixpod,
    alt: "ITC Mixpod",
  },
  {
    id: 5,
    title: "Asian Paint - Mera Wala Mood",
    tech: "HTML/CSS/JS + PHP",
    liveUrl: "https://ap-mood.onmlab.in/",
    src: Images.projects.asianPaint,
    alt: "Asian Paint",
  },
  {
    id: 6,
    title: "Cadbury 5 Star - IMC Universit",
    tech: "HTML/CSS/JS + PHP",
    liveUrl: "https://5star-university-23.onmlab.in/",
    src: Images.projects.fiveStarUniversity,
    alt: "5 Star University",
  },
  {
    id: 7,
    title: "Choclairs (React + Tailwind)",
    tech: "React + TailwindCSS",
    liveUrl: "https://choclairs-birthday-24.onmlab.in/",
    src: Images.projects.choclairs,
    alt: "Choclairs",
  },
  {
    id: 8,
    title: "Toblerone VDay 24",
    tech: "React + TailwindCSS",
    liveUrl: "https://toblerone-vday-24.onmlab.in/",
    src: Images.projects.toblerone,
    alt: "Toblerone",
  },
  {
    id: 9,
    title: "Siemens Event",
    tech: "HTML + CSS + PHP",
    liveUrl: "https://siemens-restage-launch.onmlab.in/",
    src: Images.projects.siemens,
    alt: "Siemens",
  },
  {
    id: 10,
    title: "Chocobakes",
    tech: "React + TailwindCSS",
    liveUrl: "https://chocobakes.onmlab.in/",
    src: Images.projects.chocobakes,
    alt: "Chocobakes",
  },
  {
    id: 11,
    title: "5 Star VDay 24",
    tech: "React + TailwindCSS",
    liveUrl: "https://5star-vday-24.onmlab.in/",
    src: Images.projects.fiveStarVDay,
    alt: "5 Star VDay 24",
  },
  {
    id: 12,
    title: "Cadbury Silk",
    tech: "HTML/CSS/JS + PHP",
    liveUrl: "https://www.cadburysilk.com/",
    src: Images.projects.silk,
    alt: "Silk",
  },
  {
    id: 13,
    title: "Creative Interiors",
    tech: "Next.js + TailwindCSS",
    liveUrl: "https://www.increative.in/",
    src: Images.projects.creative,
    alt: "Creative Interiors",
  },
  {
    id: 14,
    title: "Celebrations Diwali",
    tech: "React Typescript + TailwindCSS",
    liveUrl: "https://celebration-diwali-24.onmlab.in/",
    src: Images.projects.celebration,
    alt: "Celebrations Diwali",
  },
  {
    id: 15,
    title: "Maaza Bottlers Conference 25",
    tech: "React Typescript + TailwindCSS",
    liveUrl: "https://maaza-bottlers-conference-25.onmlab.in/",
    src: Images.projects.maazaBottlersConference,
    alt: "Maaza Bottlers Conference 25",
  },
  {
    id: 16,
    title: "Indianis Dentris - Cottage",
    tech: "React Typescript + TailwindCSS",
    liveUrl: "https://colgate-ind-dentris-stag-25.onmlab.in/",
    src: Images.projects.cottage,
    alt: "Indianis Dentris - Cottage",
  },
  {
    id: 17,
    title: "CDM Miniatures",
    tech: "React Typescript + TailwindCSS",
    liveUrl: "https://cdm-miniatures-ramadan-uae-stag-25.onmlab.in/",
    src: Images.projects.cdmMiniatures,
    alt: "CDM Miniatures",
  },
  {
    id: 18,
    title: "De Beers Indra Online",
    tech: "React Typescript + TailwindCSS",
    liveUrl: "https://indraonline.in/",
    src: Images.projects.debeers,
    alt: "De Beers Indra Online",
  },
  {
    id: 19,
    title: "Milka France Pokora",
    tech: "React Typescript + TailwindCSS",
    liveUrl: "https://milka-france-pokora-stag-26.onmlab.in/",
    src: Images.projects.milkaFrancePokora,
    alt: "Milka France Pokora",
  },
  {
    id: 20,
    title: "Faredown",
    tech: "HTML/CSS/JS + ASP.NET",
    liveUrl: "https://faredowntechnologies.pikateck.com/",
    src: Images.projects.faredown,
    alt: "Faredown",
  },
  {
    id: 21,
    title: "IC4 Health",
    tech: "HTML/CSS/JS + ASP.NET",
    liveUrl: "https://ic4.health/",
    src: Images.projects.ic4Health,
    alt: "IC4 Health",
  },
];
